//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkDACE.SOAPSpotBotService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParkingSpot", Namespace="http://schemas.datacontract.org/2004/07/BOT_SpotSensors")]
    [System.SerializableAttribute()]
    public partial class ParkingSpot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BatteryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ParkDACE.SOAPSpotBotService.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BatteryStatus {
            get {
                return this.BatteryStatusField;
            }
            set {
                if ((this.BatteryStatusField.Equals(value) != true)) {
                    this.BatteryStatusField = value;
                    this.RaisePropertyChanged("BatteryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ParkDACE.SOAPSpotBotService.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/BOT_SpotSensors")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPSpotBotService.ISOAPSpotBotService")]
    public interface ISOAPSpotBotService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPSpotBotService/GetParkingSpotsInfo", ReplyAction="http://tempuri.org/ISOAPSpotBotService/GetParkingSpotsInfoResponse")]
        ParkDACE.SOAPSpotBotService.ParkingSpot[] GetParkingSpotsInfo(int numberOfSpots);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPSpotBotService/GetParkingSpotsInfo", ReplyAction="http://tempuri.org/ISOAPSpotBotService/GetParkingSpotsInfoResponse")]
        System.Threading.Tasks.Task<ParkDACE.SOAPSpotBotService.ParkingSpot[]> GetParkingSpotsInfoAsync(int numberOfSpots);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPSpotBotService/GetParkingSpotsInfoXML", ReplyAction="http://tempuri.org/ISOAPSpotBotService/GetParkingSpotsInfoXMLResponse")]
        string GetParkingSpotsInfoXML(int numberOfSpots);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPSpotBotService/GetParkingSpotsInfoXML", ReplyAction="http://tempuri.org/ISOAPSpotBotService/GetParkingSpotsInfoXMLResponse")]
        System.Threading.Tasks.Task<string> GetParkingSpotsInfoXMLAsync(int numberOfSpots);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISOAPSpotBotServiceChannel : ParkDACE.SOAPSpotBotService.ISOAPSpotBotService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPSpotBotServiceClient : System.ServiceModel.ClientBase<ParkDACE.SOAPSpotBotService.ISOAPSpotBotService>, ParkDACE.SOAPSpotBotService.ISOAPSpotBotService {
        
        public SOAPSpotBotServiceClient() {
        }
        
        public SOAPSpotBotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOAPSpotBotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPSpotBotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPSpotBotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ParkDACE.SOAPSpotBotService.ParkingSpot[] GetParkingSpotsInfo(int numberOfSpots) {
            return base.Channel.GetParkingSpotsInfo(numberOfSpots);
        }
        
        public System.Threading.Tasks.Task<ParkDACE.SOAPSpotBotService.ParkingSpot[]> GetParkingSpotsInfoAsync(int numberOfSpots) {
            return base.Channel.GetParkingSpotsInfoAsync(numberOfSpots);
        }
        
        public string GetParkingSpotsInfoXML(int numberOfSpots) {
            return base.Channel.GetParkingSpotsInfoXML(numberOfSpots);
        }
        
        public System.Threading.Tasks.Task<string> GetParkingSpotsInfoXMLAsync(int numberOfSpots) {
            return base.Channel.GetParkingSpotsInfoXMLAsync(numberOfSpots);
        }
    }
}
